title: 'DLG Mechatronics Sp. z o.o - The High-Tech R&D subsidiary of PRO VITA Group.                                                              '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  lightness: 0.5
  brandStrength: 0.1756272
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#646464'
    - '#DFDFDF'
    - '#3A3A3A'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: 'DLG Mechatronics '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.43443
layout_spectrum: 0.46894
