name: 'DLG Mechatronics '
favicon: null
layout_spectrum: 0.1497
typography_spectrum: 0.68896
title: 'DLG Mechatronics Sp. z o.o. High-Tech R&D subsidiary of PRO VITA Group.                                                              '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1912'
    - '#4a505c'
    - '#fbffdb'
    - '#6aa6e3'
    - '#ab9264'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
