name: 'DLG Mechatronics '
favicon: null
layout_spectrum: 0.07808
typography_spectrum: 0.7528
title: 'DLG Mechatronics Sp. z o.o. High-Tech R&D subsidiary of PRO VITA Group.                                                              '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#656565'
    - '#ffffff'
    - '#a4d7de'
    - '#000000'
    - '#959595'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
