name: 'DLG Mechatronics '
favicon: null
layout_spectrum: 0.46894
typography_spectrum: 0.68896
title: 'DLG Mechatronics Sp. z o.o. High-Tech R&D subsidiary of PRO VITA Group.                                                              '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d9d9d9'
    - '#373737'
    - '#5a5a5a'
    - '#8f8f8f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
